services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    hostname: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - ../chain-pipe/docker/pg/data:/var/lib/postgresql/data
