[workspace]
resolver = "2"
members = ["crates/source-uniswap"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# Configuration
clap = { version = "4.5.42", default-features = false, features = [
    "derive", # Derive Parser/Args via struct attributes
    "std",    # Basic std support without color/help suggestions bloat
] }
config = "0.15.13" # TOML/ENV hierarchical config loader

# Serialization
serde = { version = "1.0.219", features = ["derive"] } # Struct ⇄ JSON/TOML/CSV
serde_json = "1.0.142"                                 # JSON de/serialization

# Error handling
eyre = "0.6.12" # Context-rich anyhow-style errors