[eth_node]
http_url = "https://reth-ethereum.ithaca.xyz/rpc"

[nats]
server_url = "nats-server:4222"
subject_input = "eth.univ2.factory.pair_created.0"
subject_output = "eth.univ2.factory.pair_created.1"
kv_bucket = "univ2_new_pairs"
stream_name = "ETH_UNIV2_FACTORY"

[uniswap_v2]
pair_address = [
    "0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc", 
    "0x0d4a11d5EEaaC28EC3F61d100daF4d40471f1852" 
]