[eth_node]
http_url = "https://reth-ethereum.ithaca.xyz/rpc"

[nats]
server_url = "nats-server:4222"
subject_input = "eth.univ2.pair_created.0"
subject_output = "eth.univ2.pair_created.1"
kv_bucket = "univ2_new_pairs"
stream_name = "ETH_UNIV2_FACTORY"