
services:
  arroyo:
    image: ghcr.io/arroyosystems/arroyo:latest
    container_name: arroyo
    hostname: arroyo
    ports:
      - "5115:5115"
    volumes:
      - ./data:/root/.config/arroyo
    networks:
      - code_rs_devcontainer_default

networks:
  code_rs_devcontainer_default:
    external: true